---

- name: 'Install NFS'
  apt:
    name: 'nfs-kernel-server'
    state: 'present'
    update_cache: true

- name: 'Check if export exists as path'
  stat:
    path: item.dir | default(item)
  loop: '{{ export_dirs }}'
  register: 'export_sources_path'
  when: export_dirs is defined

- name: 'Check if export exists as mountpoint'
  command: mountpoint -q "{{ item }}"
  loop: '{{ export_dirs }}'
  register: 'export_sources_mount'
  when: export_dirs is defined
  ignore_errors: true  # Ignore errors for non-mount points

- name: 'Add NFS Exports'
  template:
    src: 'exports.j2'
    dest: '/etc/exports'
    owner: 'root'
    group: 'root'
    mode: '0777'
  vars:
    valid_mounts: '{{ export_sources_mount.results }}'
    valid_dirs: '{{ export_sources_path.results }}'
  notify: 'reload nfs'
  when: 'export_dirs is defined'
