---

- name: 'Activating cgroup support'
  lineinfile:
    path: '/boot/cmdline.txt'
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: 'reboot'

- name: 'Disable off Swap for Kubernetes'
  lineinfile:
    path: '/etc/dphys-swapfile'
    regexp: '^CONF_SWAPSIZE='
    line: 'CONF_SWAPSIZE={{ swapsize }}'
    backrefs: true
  notify: 'reboot'
